### ISSUE TITLE
format flag does not work as expected

### ISSUE THREAD

**Issue by nikhilv** [chef/knife-hp#13]
Steps to reproduce:
0. Install chef-dk, gem install knife-hp, add credentials to knife.rb
1. knife hp server list --format json 

EXPECTED:
Output in json. The output should validate if pasted into http://jsonlint.com/.
ACTUAL:
```
Instance ID                           Name                                         Flavor  Image                                 Zone  Key Pair                                   State 
be5eb855-xxxx-yyyy-aaaa-87a490219a32  server-02f23f84-xxxx-11e4-yyyy-005056330e6d  101     5c0f583f-aaaa-bbbb-xxxx-3d1d416d31e7  az2   cmdr-030ca583-bbbb-yyyy-aaaa-005056330e6d  active
```

Reference:
http://docs.getchef.com/knife_common_options.html

Notes:
This may be a problem in some core library as I have the same problem in knife-azure. (Or I'm doing something wrong)

Other options like --no-color seem to work as expected.

**Comment by jjasghar** [comment]
We have deprecated knife-hp, please look into [knife-openstack](https://github.com/chef/knife-openstack).
