### ISSUE TITLE
knife hp server delete --node-name does not work

### ISSUE THREAD

**Issue by rtsai123** [chef/knife-hp#16]
Hi,
I tried to use the --node-name < sever_name> option when deleting a sever and it seems to not be working.  Even tried it with the --purge option as well.  Here is the command I am using:

bundle exec knife hp server delete --node-name 'rtsai_test' 

Doesn't return anything and if I issue a server list, my node is still present.

**Comment by jjasghar** [comment]
We have deprecated knife-hp, please look into [knife-openstack](https://github.com/chef/knife-openstack).
